config/routes.rb
Rails.application.routes.draw do
  resources :reactions
  resources :breakpoints do
    collection { post :import }
  end
  resources :drugs do
  	collection { post :import }
  end
  resources :mics do
  	collection { post :import }
  end
  resources :isolates do 
    collection { post :import }
  end
  resources :organisms do
    collection { post :import }
  end
  
devise_for :users
  root 'mics#index'
end

app/models/organism.rb
class Organism < ActiveRecord::Base
has_many :isolates, primary_key: 'code', foreign_key: 'organism_code'

def self.import(file)
  CSV.foreach(file.path, headers: true) do |row|
    Organism.create! row.to_hash
  end

end
end

app/controllers/organisms_controller.rb
class OrganismsController < ApplicationController
  before_action :set_organism, only: [:show, :edit, :update, :destroy]

  def index
    @organisms = Organism.all
  end

  def show
  end

  def new
    @organism = Organism.new
  end

  def edit
  end

  def create
    @organism = Organism.new(organism_params)

    respond_to do |format|
      if @organism.save
        format.html { redirect_to @organism, notice: 'Organism was successfully created.' }
        format.json { render :show, status: :created, location: @organism }
      else
        format.html { render :new }
        format.json { render json: @organism.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @organism.update(organism_params)
        format.html { redirect_to @organism, notice: 'Organism was successfully updated.' }
        format.json { render :show, status: :ok, location: @organism }
      else
        format.html { render :edit }
        format.json { render json: @organism.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @organism.destroy
    respond_to do |format|
      format.html { redirect_to organisms_url, notice: 'Organism was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
   Organism.import(params[:file])
   redirect_to organisms_url, notice: 'File imported'
  end

  private
    def set_organism
      @organism = Organism.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organism_params
      params.require(:organism).permit(:code, :name, :species, :sub_species, :organism_group, :master_group, :viridans_group, :level1, :level2, :level3, :level4)
    end
end

app/helpers/organisms_helper.rb
module OrganismsHelper
end

app/views/organisms/_form.html.erb
<%= form_for(@organism, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.form_group :code do |f| %>
      <%= f.label :code, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :code, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :name do |f| %>
      <%= f.label :name, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :species do |f| %>
      <%= f.label :species, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :species, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :sub_species do |f| %>
      <%= f.label :sub_species, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :sub_species, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :organism_group do |f| %>
      <%= f.label :organism_group, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :organism_group, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :master_group do |f| %>
      <%= f.label :master_group, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :master_group, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :viridans_group do |f| %>
      <%= f.label :viridans_group, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :viridans_group, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :level1 do |f| %>
      <%= f.label :level1, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :level1, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :level2 do |f| %>
      <%= f.label :level2, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :level2, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :level3 do |f| %>
      <%= f.label :level3, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :level3, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :level4 do |f| %>
      <%= f.label :level4, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :level4, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

  </div>

  <div class="form-actions col-md-offset-2 col-md-10">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", organisms_path, class: 'btn' %>
  </div>
<% end %>

app/views/organisms/edit.html.erb
<% @title = "Editing organism" %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/organisms/index.html.erb
<% @title = "Listing organisms" %>

<% content_for :description do %>
<!-- <p>
  <%= form_tag import_organisms_path, multipart: true do %>
	  <%= file_field_tag :file , class: 'btn btn-default btn-small pull-left' %>
	  <%= submit_tag "Bulk Import", class: 'btn btn-primary btn-small pull-left' %>
</p>    
  <% end %> -->
<% end %>

<% content_for :actions do %>
  <%= link_to new_organism_path, class: 'btn btn-primary btn-large pull-right' do %>
  <%= fa_icon_tag "plus" %> Add Organism
<% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="sheet sheet-condensed">
        <div class="sheet-inner">
          <table class="table" id="organismsdatatable">
            <thead>
              <tr>
				<th>Name</th>
                                <th>Species</th>
                                <th>Sub species</th>
                                <th>Organism group</th>
                                <th>Master group</th>
                                <th>Viridans group</th>
                                <th>Level1</th>
                                <th>Level2</th>
                                <th>Level3</th>
                                <th>Level4</th>
                                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @organisms.each do |organism| %>
		      <tr>
			        <td><%= organism.name %></td>
                                <td><%= organism.species %></td>
                                <td><%= organism.sub_species %></td>
                                <td><%= organism.organism_group %></td>
                                <td><%= organism.master_group %></td>
                                <td><%= organism.viridans_group %></td>
                                <td><%= organism.level1 %></td>
                                <td><%= organism.level2 %></td>
                                <td><%= organism.level3 %></td>
				<td><%= organism.level4 %></td>
                                <td class="actions">
                  <%= link_to fa_icon_tag("eye"), organism, rel: 'tooltip', title: 'Show' %>
                  <%= link_to fa_icon_tag("pencil"), edit_organism_path(organism), rel: 'tooltip', title: 'Edit' %>
                  <%= link_to fa_icon_tag("trash-o"), organism, rel: 'tooltip', title: 'Delete',
                  data: { confirm: 'Are you sure?' }, method: :delete %>
                </td>
              </tr>
              <% end %>
              <% if @organisms.length == 0 %>
              <tr><td colspan=42 class='text-center'>No organisms.</td></tr>
              <% end %>
            </tbody>
          </table>
        </div><!-- /.sheet-inner -->
      </div><!-- /.sheet -->

                </div>
  </div>
</div>

app/views/organisms/new.html.erb
<% @title = "New organism" %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/organisms/show.html.erb
<% @title = "Showing organism" %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="form-horizontal">
                <div class="form-group">
          <label class="col-md-2 form-label">Code</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @organism.code %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Name</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @organism.name %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Species</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @organism.species %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Sub species</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @organism.sub_species %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Organism group</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @organism.organism_group %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Master group</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @organism.master_group %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Viridans group</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @organism.viridans_group %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Level1</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @organism.level1 %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Level2</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @organism.level2 %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Level3</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @organism.level3 %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Level4</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @organism.level4 %>
            </span>
          </div>
        </div>

                <div class="form-actions col-md-offset-2">
          <%= link_to fa_icon_tag("pencil") + ' Edit', edit_organism_path(@organism), class: 'btn btn-primary' %>
          <%= link_to 'Back', organisms_path, class: 'btn' %>
        </div>
      </div>
    </div>
  </div>
</div>