config/routes.rb
Rails.application.routes.draw do
  resources :reactions
  resources :breakpoints do
    collection { post :import }
  end
  resources :drugs do
  	collection { post :import }
  end
  resources :mics do
  	collection { post :import }
  end
  resources :isolates do 
    collection { post :import }
  end
  resources :organisms do
    collection { post :import }
  end
  
devise_for :users
  root 'mics#index'
end

app/models/isolate.rb
class Isolate < ActiveRecord::Base
belongs_to :organism, primary_key: 'code', foreign_key: 'organism_code'
has_many :mic

def self.import(file)
  CSV.foreach(file.path, headers: true) do |row|
    Isolate.create! row.to_hash
  end
end

end

app/controllers/isolates_controller.rb
class IsolatesController < ApplicationController
  before_action :set_isolate, only: [:show, :edit, :update, :destroy]

  def index
    @isolates = Isolate.all
  end

  def show
  end

  def new
    @isolate = Isolate.new
  end

  def edit
  end

  def create
    @isolate = Isolate.new(isolate_params)

    respond_to do |format|
      if @isolate.save
        format.html { redirect_to @isolate, notice: 'Isolate was successfully created.' }
        format.json { render :show, status: :created, location: @isolate }
      else
        format.html { render :new }
        format.json { render json: @isolate.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @isolate.update(isolate_params)
        format.html { redirect_to @isolate, notice: 'Isolate was successfully updated.' }
        format.json { render :show, status: :ok, location: @isolate }
      else
        format.html { render :edit }
        format.json { render json: @isolate.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @isolate.destroy
    respond_to do |format|
      format.html { redirect_to isolates_url, notice: 'Isolate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 def import
   Isolate.import(params[:file])
   redirect_to isolates_url, notice: 'File imported'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_isolate
      @isolate = Isolate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def isolate_params
      params.require(:isolate).permit(:isolate_id, :collection, :site, :study_year, :bank, :organism_code)
    end
end

app/helpers/isolates_helper.rb
module IsolatesHelper
end

app/views/isolates/_form.html.erb
<%= form_for(@isolate, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.form_group :isolate_id do |f| %>
      <%= f.label :isolate_id, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :isolate_id, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :collection do |f| %>
      <%= f.label :collection, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :collection, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :site do |f| %>
      <%= f.label :site, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :site, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :study_year do |f| %>
      <%= f.label :study_year, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :study_year, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :bank do |f| %>
      <%= f.label :bank, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :bank, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :organism_code do |f| %>
      <%= f.label :organism_code, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.collection_select(:organism_code, Organism.all, :code, :name) %>
        <%= f.error_messages %>
      </div>
    <% end %>

  </div>

  <div class="form-actions col-md-offset-2 col-md-10">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", isolates_path, class: 'btn' %>
  </div>
<% end %>

app/views/isolates/edit.html.erb
<% @title = "Editing isolate" %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/isolates/index.html.erb
<% @title = "Listing isolates" %>

<% content_for :description do %>
<!-- <p>
  <%= form_tag import_isolates_path, multipart: true do %>
	  <%= file_field_tag :file , class: 'btn btn-default btn-small pull-left' %>
	  <%= submit_tag "Bulk Import", class: 'btn btn-primary btn-small pull-left' %>
</p>    
  <% end %> -->
<% end %>

<% content_for :actions do %>
<%= link_to new_isolate_path, class: 'btn btn-primary btn-large pull-right' do %>
<%= fa_icon_tag "plus" %> Add Isolate
<% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="sheet sheet-condensed">
        <div class="sheet-inner">
          <table class="table" id="isolatesdatatable">
            <thead>
              <tr>
                                <th>Isolate</th>
                                <th>Collection</th>
                                <th>Site</th>
                                <th>Study year</th>
                                <th>Bank</th>
                                <th>Organism code</th>
                                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @isolates.each do |isolate| %>
              <tr>
                                <td><%= isolate.isolate_id %></td>
                                <td><%= isolate.collection %></td>
                                <td><%= isolate.site %></td>
                                <td><%= isolate.study_year %></td>
                                <td><%= isolate.bank %></td>
				<td><%= isolate.organism_code %></td>
                                <td class="actions">
                  <%= link_to fa_icon_tag("eye"), isolate, rel: 'tooltip', title: 'Show' %>
                  <%= link_to fa_icon_tag("pencil"), edit_isolate_path(isolate), rel: 'tooltip', title: 'Edit' %>
                  <%= link_to fa_icon_tag("trash-o"), isolate, rel: 'tooltip', title: 'Delete',
                  data: { confirm: 'Are you sure?' }, method: :delete %>
                </td>
              </tr>
              <% end %>
              <% if @isolates.length == 0 %>
              <tr><td colspan=42 class='text-center'>No isolates.</td></tr>
              <% end %>
            </tbody>
          </table>
        </div><!-- /.sheet-inner -->
      </div><!-- /.sheet -->

                </div>
  </div>
</div>

app/views/isolates/new.html.erb
<% @title = "New isolate" %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/isolates/show.html.erb
<% @title = "Showing isolate" %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="form-horizontal">
                <div class="form-group">
          <label class="col-md-2 form-label">Isolate</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @isolate.isolate_id %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Collection</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @isolate.collection %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Site</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @isolate.site %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Study year</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @isolate.study_year %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Bank</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @isolate.bank %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Organism code</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>		    
              <%= @isolate.organism_code %>
            </span>
          </div>
        </div>

                <div class="form-actions col-md-offset-2">
          <%= link_to fa_icon_tag("pencil") + ' Edit', edit_isolate_path(@isolate), class: 'btn btn-primary' %>
          <%= link_to 'Back', isolates_path, class: 'btn' %>
        </div>
      </div>
    </div>
  </div>
</div>