config/routes.rb
Rails.application.routes.draw do
  resources :reactions
  resources :breakpoints do
    collection { post :import }
  end
  resources :drugs do
  	collection { post :import }
  end
  resources :mics do
  	collection { post :import }
  end
  resources :isolates do 
    collection { post :import }
  end
  resources :organisms do
    collection { post :import }
  end
  
devise_for :users
  root 'mics#index'
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :set_reaction, only: [:show, :edit, :update, :destroy]

  # GET /reactions
  # GET /reactions.json
  def index
    @reactions = Reaction.all
  end

  # GET /reactions/1
  # GET /reactions/1.json
  def show
  end

  # GET /reactions/new
  def new
    @reaction = Reaction.new
  end

  # GET /reactions/1/edit
  def edit
  end

  # POST /reactions
  # POST /reactions.json
  def create
    @reaction = Reaction.new(reaction_params)

    respond_to do |format|
      if @reaction.save
        format.html { redirect_to @reaction, notice: 'Reaction was successfully created.' }
        format.json { render :show, status: :created, location: @reaction }
      else
        format.html { render :new }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reactions/1
  # PATCH/PUT /reactions/1.json
  def update
    respond_to do |format|
      if @reaction.update(reaction_params)
        format.html { redirect_to @reaction, notice: 'Reaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @reaction }
      else
        format.html { render :edit }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reactions/1
  # DELETE /reactions/1.json
  def destroy
    @reaction.destroy
    respond_to do |format|
      format.html { redirect_to reactions_url, notice: 'Reaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reaction
      @reaction = Reaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reaction_params
      params.require(:reaction).permit(:authority, :publication, :delivery_mechanism, :infection_type, :isolate_id, :drug_id, :reaction, :footnote, :eligible_interpretations, :rule_row_number, :used_surrogate_drug_id, :used_surrogate_drug_ordinal, :used_surrogate_rule_type)
    end
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/reactions/_form.html.erb
<%= form_for(@reaction, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.form_group :authority do |f| %>
      <%= f.label :authority, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :authority, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :publication do |f| %>
      <%= f.label :publication, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :publication, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :delivery_mechanism do |f| %>
      <%= f.label :delivery_mechanism, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :delivery_mechanism, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :infection_type do |f| %>
      <%= f.label :infection_type, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :infection_type, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :isolate_id do |f| %>
      <%= f.label :isolate_id, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :isolate_id, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :drug_id do |f| %>
      <%= f.label :drug_id, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :drug_id, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :reaction do |f| %>
      <%= f.label :reaction, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :reaction, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :footnote do |f| %>
      <%= f.label :footnote, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :footnote, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :eligible_interpretations do |f| %>
      <%= f.label :eligible_interpretations, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :eligible_interpretations, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :rule_row_number do |f| %>
      <%= f.label :rule_row_number, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :rule_row_number, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :used_surrogate_drug_id do |f| %>
      <%= f.label :used_surrogate_drug_id, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.number_field :used_surrogate_drug_id, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :used_surrogate_drug_ordinal do |f| %>
      <%= f.label :used_surrogate_drug_ordinal, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :used_surrogate_drug_ordinal, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

    <%= f.form_group :used_surrogate_rule_type do |f| %>
      <%= f.label :used_surrogate_rule_type, class: 'control-label col-md-2' %>
      <div class='col-md-8'>
        <%= f.text_field :used_surrogate_rule_type, class: 'form-control' %>
        <%= f.error_messages %>
      </div>
    <% end %>

  </div>

  <div class="form-actions col-md-offset-2 col-md-10">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", reactions_path, class: 'btn' %>
  </div>
<% end %>

app/views/reactions/edit.html.erb
<% @title = "Editing reaction" %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/reactions/index.html.erb
<% @title = "Listing reactions" %>

<% content_for :description do %>
<p>Test results go here after import</p>
<% end %>

<% content_for :actions do %>
<%= link_to new_reaction_path, class: 'btn btn-primary btn-large pull-right' do %>
<%= fa_icon_tag "plus" %> Add Reaction
<% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="sheet sheet-condensed">
        <div class="sheet-inner">
          <table class="table" id="maindatatable">
            <thead>
              <tr>
                                <th>Delivery mechanism</th>
                                <th>Infection type</th>
                                <th>Isolate</th>
                                <th>Drug</th>
                                <th>Reaction</th>
                                <th>Footnote</th>
                                <th>Eligible interpretations</th>
                                <th>Used surrogate drug</th>
                                <th>Used surrogate drug ordinal</th>
                                <th>Used surrogate rule type</th>
                                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @reactions.each do |reaction| %>
              <tr>
                                <td><%= reaction.delivery_mechanism %></td>
                                <td><%= reaction.infection_type %></td>
                                <td><%= reaction.isolate_id %></td>
                                <td><%= reaction.drug_id %></td>
                                <td><%= reaction.reaction %></td>
                                <td><%= reaction.footnote %></td>
                                <td><%= reaction.eligible_interpretations %></td>
                                <td><%= reaction.used_surrogate_drug_id %></td>
                                <td><%= reaction.used_surrogate_drug_ordinal %></td>
                                <td><%= reaction.used_surrogate_rule_type %></td>
                                <td class="actions">
                  <%= link_to fa_icon_tag("eye"), reaction, rel: 'tooltip', title: 'Show' %>
                  <%= link_to fa_icon_tag("pencil"), edit_reaction_path(reaction), rel: 'tooltip', title: 'Edit' %>
                  <%= link_to fa_icon_tag("trash-o"), reaction, rel: 'tooltip', title: 'Delete',
                  data: { confirm: 'Are you sure?' }, method: :delete %>
                </td>
              </tr>
              <% end %>
              <% if @reactions.length == 0 %>
              <tr><td colspan=42 class='text-center'>No reactions.</td></tr>
              <% end %>
            </tbody>
          </table>
        </div><!-- /.sheet-inner -->
      </div><!-- /.sheet -->

                </div>
  </div>
</div>

app/views/reactions/new.html.erb
<% @title = "New reaction" %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/reactions/show.html.erb
<% @title = "Showing reaction" %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="form-horizontal">
                <div class="form-group">
          <label class="col-md-2 form-label">Authority</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @reaction.authority %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Publication</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @reaction.publication %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Delivery mechanism</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @reaction.delivery_mechanism %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Infection type</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @reaction.infection_type %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Isolate</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @reaction.isolate_id %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Drug</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @reaction.drug_id %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Reaction</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @reaction.reaction %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Footnote</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @reaction.footnote %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Eligible interpretations</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @reaction.eligible_interpretations %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Rule row number</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @reaction.rule_row_number %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Used surrogate drug</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @reaction.used_surrogate_drug_id %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Used surrogate drug ordinal</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @reaction.used_surrogate_drug_ordinal %>
            </span>
          </div>
        </div>

                <div class="form-group">
          <label class="col-md-2 form-label">Used surrogate rule type</label>
          <div class="col-md-10 form-control uneditable-input">
            <span>
              <%= @reaction.used_surrogate_rule_type %>
            </span>
          </div>
        </div>

                <div class="form-actions col-md-offset-2">
          <%= link_to fa_icon_tag("pencil") + ' Edit', edit_reaction_path(@reaction), class: 'btn btn-primary' %>
          <%= link_to 'Back', reactions_path, class: 'btn' %>
        </div>
      </div>
    </div>
  </div>
</div>