config/routes.rb
Rails.application.routes.draw do
  resources :reactions
  resources :breakpoints do
    collection { post :import }
  end
  resources :drugs do
  	collection { post :import }
  end
  resources :mics do
  	collection { post :import }
  end
  resources :isolates do 
    collection { post :import }
  end
  resources :organisms do
    collection { post :import }
  end
  
devise_for :users
  root 'mics#index'
end

app/views/layouts/_base.html.erb
<!DOCTYPE html>
<%= html_tag :lang => "en" do %>
  <head>
    <meta charset="utf-8">
    <title><%= [@title, app_name].compact.join(" - ") %></title>
    <%= csrf_meta_tags %>

    <!-- Ensure devices display responsive pages properly -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le fonts -->
    <%= stylesheet_link_tag "//fonts.googleapis.com/css?family=Droid+Sans:400,700" %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Lato:300,400,700,900' %>

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield :styles %>

    <!-- This is for Google Maps integration, you can safely remove if not using Google Maps -->
    <%= javascript_include_tag "//maps.google.com/maps/api/js?sensor=true&.js" %>

    <!-- Le fav and touch icons -->
    <%= favicon_link_tag %>
    <%# favicon_link_tag "apple-touch-icon.png", :rel => "apple-touch-icon" %>

    <%= yield :head %>
  </head>
  <body class="<%= yield (:body_class) %>">
    <%= render "layouts/navbar" %>

    <header>
      <%= yield :header %>
    </header>

    <%= yield :banner %>

    <div id="main" class="container-fluid">
      <div class="row">
        <%= yield %>
      </div> <!-- /.container -->
    </div> <!-- /#main -->

    <%= render "layouts/footer" %>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" %>

    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>

  </body>
<% end %>

app/views/layouts/_centered.html.erb
<!DOCTYPE html>
<%= html_tag :lang => "en" do %>
  <head>
    <meta charset="utf-8">
    <title><%= [@title, app_name].compact.join(" - ") %></title>
    <%= csrf_meta_tags %>

    <!-- Ensure devices display responsive pages properly -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le fonts -->
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Droid+Sans:400,700" %>

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield :styles %>

    <!-- Le fav and touch icons -->
    <%= favicon_link_tag %>
    <%# favicon_link_tag "apple-touch-icon.png", :rel => "apple-touch-icon" %>

    <%= yield :head %>
  </head>
  <body class="<%= yield (:body_class) %>">
    <div id="main" class='vertical-center'>
      <div class="container">
        <div class='row'>
          <%= render "layouts/flashes" %>
        </div>
        <%= yield %>
      </div> <!-- /.container -->
    </div> <!-- /#main -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>

  </body>
<% end %>

app/views/layouts/_flashes.html.erb
<% if alert %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= fa_icon_tag "remove" %> <%= alert %>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= fa_icon_tag "info-sign" %> <%= notice %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-lg-4 text-xs-center text-md-left">
          <section>
            <h4>About</h4>
            <a href="#">About My App</a> <br>
            <a href="#">Privacy</a> <br>
            <a href="#">Terms</a>
          </section>
        </div>
        <div class="col-sm-12 col-lg-4 text-xs-center text-md-left">
          <section>
            <h4>Social</h4>
            <a href="#">Blog</a> <br>
            <a href="#">Twitter</a> <br>
            <a href="#">Facebook</a><br>
            <a href="#">Contact Us</a>
          </section>
        </div>
        <div class="col-sm-12 col-lg-4 text-xs-center text-md-left">
          <section>
            <h4>Quick Links</h4>
            <a href="#">Login</a> <br>
            <a href="#">Sign up</a> <br>
          </section>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_minimal.html.erb
<!DOCTYPE html>
<%= html_tag :lang => "en" do %>
  <head>
    <meta charset="utf-8">
    <title><%= [@title, app_name].compact.join(" - ") %></title>
    <%= csrf_meta_tags %>

    <!-- Ensure devices display responsive pages properly -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le fonts -->
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Droid+Sans:400,700" %>

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield :styles %>

    <!-- Le fav and touch icons -->
    <%= favicon_link_tag %>
    <%# favicon_link_tag "apple-touch-icon.png", :rel => "apple-touch-icon" %>

    <%= yield :head %>
  </head>
  <body class="<%= yield (:body_class) %>">
    <%= render "layouts/navbar" %>

    <div id="main" class="container-fluid">
      <div class="row">
        <%= yield %>
      </div> <!-- /.container -->
    </div> <!-- /#main -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <!-- This is for Google Maps integration, you can safely remove if not using Google Maps -->
    <%= javascript_include_tag "//maps.google.com/maps/api/js?sensor=true&.js" %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" %>
    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>

  </body>
<% end %>

app/views/layouts/_navbar.html.erb
<%# Top navigation bar containing the main menu of your app. %>
<div class='container'>
  <%= yield :navbar %>
</div>

app/views/layouts/_sidenav.html.erb
<div class="nav-side-menu">
<div class="navbar-header">
  <div class="profile">
    <%= random_avatar 60, "img-circle profile-image" %>
    <div class="profile-body">
      <h4>Fill Murray</h4>

      <div class="user-links">
        <a class="btn btn-link btn-flat btn-xs btn-borderless" href="#" data-placement="bottom" data-toggle="tooltip" data-original-title="Messages"><i class="fa fa-envelope"></i></a>
        <a class="btn btn-link btn-flat btn-xs btn-borderless" href="#" data-placement="bottom" data-toggle="tooltip" data-original-title="Profile"><i class="fa fa-user"></i></a>
        <a class="btn btn-link btn-flat btn-xs btn-borderless" href="#" data-placement="bottom" data-toggle="tooltip" data-original-title="Settings"><i class="fa fa-cog"></i></a>
        <a class="btn btn-link btn-flat btn-xs btn-borderless" href="#" data-placement="bottom" data-toggle="tooltip" data-original-title="Logout"><i class="fa fa-sign-out"></i></a>
      </div>
    </div>
  </div>
  <i class="navbar-toggle collapsed fa fa-bars" data-toggle="collapse" data-target="#menu-content"></i>
</div>

<ul id="menu-content" class="nav navbar-collapse">
  <li>
    <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Menu Example<span class="fa arrow"></span></a>
    <ul class="nav nav-second-level collapse" aria-expanded="false">
      <li>
        <a href="#" class="active">Second Level Item</a>
      </li>
      <li>
        <a href="#" class="active">Second Level Item</a>
      </li>
      <li>
        <a href="#">Third Level <span class="fa arrow"></span></a>
        <ul class="nav nav-third-level">
          <li>
            <a href="#" class="active">Third Level Item</a>
          </li>
          <li>
            <a href="#" class="active">Third Level Item</a>
          </li>
          <li>
            <a href="#" class="active">Third Level Item</a>
          </li>
          <li>
            <a href="#">Fourth Level <span class="fa arrow"></span></a>
            <ul class="nav nav-fourth-level">
              <li>
                <a href="#" class="active">Fourth Level Item</a>
              </li>
              <li>
                <a href="#" class="active">Fourth Level Item</a>
              </li>
              <li>
                <a href="#" class="active">Fourth Level Item</a>
              </li>
              <li>
                <a href="#" class="active">Fourth Level Item</a>
              </li>
            </ul>
          </li>
        </ul>
        <!-- /.nav-third-level -->
      </li>
    </ul>
    <!-- /.nav-second-level -->
  </li>
  <li class="nav-side-menu-footer">
    <div>
      <small>
        <strong>3 Users</strong> / 10 Users
        <span class="pull-right">
          <button class='btn btn-outline-info btn-flat btn-xs'><i class="fa fa-plus"></i></button>
        </span>
      </small>
    </div>
    <div class="progress progress-mini">
      <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 33%"></div>
    </div>
    <div class='text-center'>
      100% operatinal capacity
    </div>
  </li>
</ul>
</div>

app/views/layouts/_user_nav.html.erb
<%# Links for current user. %>
<nav class='navbar'>
  <div class='navbar-brand'>
	  <%= link_to 'JMI Homework', root_path %>  |
	  <%= link_to 'Organisms', organisms_path %>  |
	  <%= link_to 'Isolates', isolates_path %>  |
    <%= link_to 'Mics', mics_path %>  |
    <%= link_to 'Drugs', drugs_path %>  |
    <%= link_to 'Breakpoints', breakpoints_path %>  |

  </div>
  <div class="navbar-text pull-right">
  
    <%= fa_icon_tag "user" %> Welcome, <strong><%= current_user.email %></strong>
    <span class="divider">|</span>
    <%= link_to "Settings", edit_user_registration_path %>
  
  </div>
</nav>

app/views/layouts/application.html.erb
<% content_for :navbar, render("layouts/user_nav") %>

<%= render :layout => "layouts/minimal" do %>
  <div class="page-header">
    <div class='container'>
      <div class="row row-same-height">
        <div class="col-md-12 col-sm-height col-middle">
          <h2 class='m0'><%= @title %></h2>
          <%= yield :description %>
        </div>
        <div class="col-md-2 col-sm-height col-middle">
          <%= yield :actions %>
        </div>
      </div>
    </div>
  </div><!-- /.page-header -->

  <div class='container'>
    <div class='row'>
      <%= render "layouts/flashes" %>
    </div>
  </div>

  <div class='container-fluid'>
      <div id="content" class="col-md-12">
        <%= yield %>
      </div> <!-- /#content -->
  </div>
<% end %>

app/views/layouts/devise.html.erb
<%= render :layout => "layouts/centered" do %>
  <div class='row'>
    <div id="content" class="col-md-12">
      <%= yield %>
    </div> <!-- /#content -->
  </div>
<% end %>

app/views/layouts/email.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title><%= @title || message.subject %></title>
    <style type="text/css">

      /* Take care of image borders and formatting */
      img     { max-width:600px !important; outline:none; text-decoration:none; -ms-interpolation-mode: bicubic; }
      a img   { border:none; }

      /* Fix Apple contact links and hide the preheader */
      .applefix a           {color:#888888; text-decoration: none;}
      span[class="preheader"] { display:none; }

      /* Responsive Styles */
      @media only screen and (max-width:600px) {
        img                             { width:100% !important; height:auto !important; }
        img[class="columnImage"]        { height:auto !important; max-width:480px !important; width:100% !important; }
        table[id="emailContainer"]      { width:100% !important; }
        table[class="columnContainer"]  { width:100% !important; }
        table[class="mobileButton"]     { width:60% !important; }
        td[class="columnSingle"]        { display:block !important; width:100% !important; }
      }

    </style>
  </head>

  <body bgcolor="#efefef" style="background-color:#efefef; -webkit-text-size-adjust: none;">

    <span class="preheader" style="display:none; color:#efefef;"><%= @title || message.subject %></span>

    <table align="center" border="0" cellpadding="0" cellspacing="0" width="600" id="emailContainer" style="display:block; max-width:600px; background-color:#efefef;">
      <tr>
        <td align="center" valign="top">
          <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;">
            <tr>
              <td>
                <%= render partial: 'emails/email_header', locals: { title: message.subject } %>
              </td>
            </tr>
            <%= yield %>
            <tr>
              <td>
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:600px;">
                  <tr>
                    <td align="center" valign="top">
                      <%= render partial: 'emails/email_footer' %>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>

  </body>
</html>

app/views/layouts/home.html.erb
<% content_for :navbar do %>
<div class="navbar">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a href="#" class="navbar-brand">Your Company</a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li class="active">
        <a href="#">Home</a>
      </li>
      <li>
        <a href="#">About</a>
      </li>
      <li>
        <a href="#">Contact</a>
      </li>
      <li>
        <a href="#">Login</a>
      </li>
      <li>
        <button class='btn btn-outline-primary sign-up'>Sign Up</button>
      </li>
    </ul>
  </div>
</div>
<% end %>

<%= render :layout => "layouts/base" do %>
  <%= yield %>
<% end %>

app/views/layouts/sidenav.html.erb
<%= render :layout => "layouts/minimal" do %>
<%= render partial: "layouts/sidenav" %>
<div class='main-content'>
  <nav class="navbar navbar-default navbar-shadow" role="navigation">
    <div class="navbar-inner">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-content-nav">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="main-content-nav">
        <ul class="nav navbar-nav">
          <li class=""><a href="#">Servers</a></li>
          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Clusters <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li class=""><a href="#">Cluster 1</a></li>
              <li class=""><a href="#">Cluster 2</a></li>
              <li class=""><a href="#">Cluster 3</a></li>
              <li class=""><a href="#">Cluster 4</a></li>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li>
            <form class="navbar-form search-form" role="search">
              <input type="text" class="form-control" id="searchbox" placeholder="Search">
              <span class="search-button"><i class="fa fa-search"></i></span>
            </form>
          </li>
          <%= yield :navbar %>
          <li class='navbar-form'>
            <div class="btn-group" data-toggle="buttons">
              <label class="btn btn-default active">
                <input type="radio" name="options" id="option1" autocomplete="off" checked=""> <i class="fa fa-home"></i>
              </label>
              <label class="btn btn-default">
                <input type="radio" name="options" id="option2" autocomplete="off"> <i class="fa fa-envelope"></i>
              </label>
              <label class="btn btn-default">
                <input type="radio" name="options" id="option3" autocomplete="off"> <i class="fa fa-user"></i>
              </label>
            </div>
          </li>
          <li class="dropdown">
            <button class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-fw fa-cog"></i>
              <span class="caret caret-light"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Site management</a></li>
              <li><a href="#">User management</a></li>
              <li><a href="#">Settings</a></li>
            </ul>
          </li>
          <li class="dropdown notifications">
            <button class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-fw fa-bell"></i>
              <span class="badge badge-sm">2</span><span class="caret caret-light"></span>
              <span class="visible-xs-inline">Notifications</span>
            </button>
            <!-- dropdown -->
            <ul class="dropdown-menu">
              <li>
                <div class="panel">
                  <div class="panel-heading text-center">
                    <small><strong>You have <span>2</span> notifications</strong></small>
                  </div>
                  <div class="list-group">
                    <a href="#" class="media list-group-item">
                      <span class="pull-left">
                        <%= random_avatar 32, "media-object img-circle" %>
                      </span>
                      <span class="media-body">
                        <p>My name is Inigo Montoya.</p>
                        <small class="text-muted">10 minutes ago</small>
                      </span>
                    </a>
                    <a href="" class="media list-group-item">
                      <span class="media-body">
                        <div>
                          <p>You've reached your space quota!</p>
                          <div class="progress progress-sm m0">
                            <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;"><span class="sr-only">100% Complete</span></div>
                          </div>
                        </div>
                        <small class="text-muted">12 hours ago</small>
                      </span>
                    </a>
                  </div>
                  <div class="panel-footer">
                    <a href="#" class="pull-right"><i class="fa fa-cog"></i></a>
                    <a href="#">View all Notifications</a>
                  </div>
                </div>
              </li>
            </ul>
            <!-- / dropdown -->
          </li>
          <li class="dropdown user-nav">
            <button class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= random_avatar 34, "avatar img-rounded" %>
              <span class="caret caret-light"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li class="profile-header">
                <%= random_avatar 120, "avatar img-rounded" %>
                <p class="m0 p0">
                  Fill Murray
                </p>
                <p class="small m0 p0">Premium Account</p>
              </li>
              <li class="profile-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat"><small>Edit Profile</small></a>
                </div>
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat small"><small>Log Out</small></a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.navbar-inner -->
  </nav>

  <%= yield %>
</div>
<% end %>